### ISSUE TITLE
[ENH]: Update source dataset to fMRIPrep 20.2.0 LTS on open OSF

### ISSUE THREAD

**Issue by jerdra** [carpentries-incubator/SDC-BIDS-fMRI#21]
The current dataset used in the lessons is running a (very) legacy version of fMRIPrep (0.4.0). Since then, fMRIPrep has changed its output structure to follow the BIDS derivatives convention more closely and as a result the outputs learners are dealing with during these lessons do not map to what they would see when running their own analyses. 

Ideally we'd use pre-existing fMRIPrep 20.2.0 LTS outputs, however with the requirement that the dataset must have a case-control comparison with resting state data and available task data we've decided to run the subset of individuals we use in this lesson through LTS and host the data on OSF. 

Instead of using the AWS S3 cli to access data, we will switch over to using Datalad to follow more closely to [SDC-BIDS-IntroMRI](https://github.com/carpentries-incubator/SDC-BIDS-IntroMRI); the pre-requisite to this course. 

## TODO:

- [x] Set up fMRIPrep 20.2.3 LTS run
- [x] Run data through fMRIPrep 20.2.3 LTS
- [x] Host data on OSF
- [ ] #31
- [ ] Deprecate setup scripts that rely on AWS CLI
- [ ] Update Data Carpentry markdown to reflect changes in Jupyter
